apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: gremlins
    app.kubernetes.io/component: {{ .Values.nameOverride }}
    app.kubernetes.io/instance: {{ .Values.nameOverride }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ .Values.nameOverride }}
    app.kubernetes.io/part-of: {{ .Values.nameOverride }}-app
  name: {{ .Values.nameOverride }}-ssl
  namespace: devops
spec:
  host: gremlins.dorneean.ro
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ .Values.nameOverride }}
    weight: 100
  wildcardPolicy: None
