kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    app: {{ .Values.nameOverride }}
    app.kubernetes.io/component: {{ .Values.nameOverride }}
    app.kubernetes.io/instance: {{ .Values.nameOverride }}
    app.kubernetes.io/name: {{ .Values.nameOverride }}
    app.kubernetes.io/part-of: {{ .Values.nameOverride }}-app
spec:
  to:
    kind: Service
    name: {{ .Values.nameOverride }}
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None