kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    app: {{ .Values.nameOverride }}
    app.kubernetes.io/component: {{ .Values.nameOverride }}
    app.kubernetes.io/instance: {{ .Values.nameOverride }}
    app.kubernetes.io/name: {{ .Values.nameOverride }}
    app.kubernetes.io/part-of: {{ .Values.nameOverride }}-app
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    app: {{ .Values.nameOverride }}
    deploymentconfig: {{ .Values.nameOverride }}
