library identifier: "pipeline-library@master", retriever: modernSCM(
  [$class: "GitSCMSource",
   remote: "https://github.com/redhat-cop/pipeline-library.git"])

pipeline{
    agent{
        label "nodejs"
    }
    stages{
        stage("Checkout code"){
            steps{
                git 'https://github.com/adynetro/openshift-demo-pipeline.git'
            }
        }
        stage("SBOM Package scan"){
          steps{
            sh 'cd gremlins && npm install'
            sh 'npm set prefix ~/.npm-global && npm install --global @cyclonedx/cyclonedx-npm && cd gremlins && sh -c ~/.npm-global/bin/cyclonedx-npm --output-file bom.json'
            dependencyTrackPublisher artifact: "gremlins/bom.json", autoCreateProjects: false, dependencyTrackApiKey: '', dependencyTrackFrontendUrl: '', dependencyTrackUrl: '', projectId: 'f8fac26f-6c5b-47a0-92e1-dd0aa6a15176', synchronous: false
          }
        }
        stage("Build code"){
            steps{
                sh '''
                cd gremlins
                npm run-script build
                '''
            }
        }
        stage("Binary build"){
            steps{
                binaryBuild([
                        buildConfigName: "gremlins-build",
                        buildFromFlag  : "--from-dir",
                        buildFromPath  : "${WORKSPACE}/gremlins/build/"
                ])
            }
        }
    }
}
