apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gremlins
  namespace: argocd   
spec:
  project: gremlins
  source:
    repoURL: https://github.com/adynetro/openshift-demo-pipeline.git
    targetRevision: master
    path: helm/gremlins
  destination:
    server: https://kubernetes.default.svc
    namespace: devops
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
