apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gremlins
  namespace: argocd 
spec:
  description: Test Project for Gremlins
  sourceRepos:
    - https://github.com/adynetro/openshift-demo-pipeline.git
  destinations:
    - namespace: devops
      server: https://kubernetes.default.svc
  roles:
    - description: project role to create and sync apps from a CI/CD pipeline
      name: create-sync
      policies:
      - p, proj:gremlins:create-sync, applications, get, gremlins/*, allow
      - p, proj:gremlins:create-sync, applications, create, gremlins/*, allow
      - p, proj:gremlins:create-sync, applications, update, gremlins/*, allow
      - p, proj:gremlins:create-sync, applications, delete, gremlins/*, allow
      - p, proj:gremlins:create-sync, applications, sync, gremlins/*, allow
