kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "gremlins-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/adynetro/openshift-demo-pipeline"
      ref: "master"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/Jenkinsfile